language: node_js
node_js:
- node
install:
- yarn install --frozen-lockfile
- yarn test
- yarn build
deploy:
  provider: s3
  access_key_id: AKIAI6IKW3HG5C6XRL4A
  secret_access_key:
    secure: B3Nv/u8kXJF1S37768FvHC7bSiIvV7AhHVF5ujvY/fy0zC0LP8XDXwJVeIiZo1oe4mI/QqjICtLlIjJpRFdTeVCbHWygBoIU5YROVj8AByeRZ7Dgq94vBMnGH1RkWC39zqNrWHuMbGtJsFBs2058IwLnaHBB1X4f9mMkenRQ24dAACc5IplzMhld77mGmdUQA1F4qiy2l8qfC6UnVYBClkuJ7gBBOqrDFUQbqTLB6b/5+2muRJNID4Wff9q45V6tKKGktZn0EM/WGbOBbO1b+ym1BoJsmdEvZCciUPWHdsFicfSNmKdWQZez1qUZZzMDUI7MrxHORBSn7hZJNI4vcOFggvF8sid1aGrfuW4TqjJv2e5zW2TwVL9Vowm2orrY97q1reE2sqwhYDKtiuBbI/r8XrOK1YTVQn2QBfe3Gpfqb+p0BOqUezUZJI2UJyxuHI1GFgP6H1NZWXi9EjoQoOP8D963bFbOo5W3n8xYmhaaxC9IUu55O45A3hajjuLTmzAdw34tSURN1HfG4eBLAX3dMGiMG6sekAs3oh38mal8+k/hnnqJHliMa7rxq4PxOBAwSicsxejjNnP6qzr+on1vzH0omcZwSKrAj8AMAlevWlRNNzsi34f944067X0BPEJpJbYoD1Q8BpI1UQcf1UJAEf9ArEKhB8uJWz7id3s=
  bucket: gaelmusi
  skip_cleanup: true
  local_dir: build
